### ISSUE TITLE
zimwriterfs does not re-encode filename coming from HFS+

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#1]
Using zimwriterfs (with Docker) on OSX generates filename on the filesystem using UTF8 NFD. The URL schema enforces UTF8 NFC. As a conclusion we get "wrong urls" generated in javascript.

Maybe the zimwriterfs should offer an option to force re-encoding of filename.

**Comment by kelson42** [comment]
We don't provide a Docker supporting natively MacOS, so without more details, it is difficult here to know exactly what has been done or what happened.

**Comment by kelson42** [comment]
@rgaudin Sure about closing that one?

**Comment by rgaudin** [comment]
It's probably still valid but the odds of this impacting someone seems ultra low. I know because I am the one who reported it to you originally. I think it should be closed.
