### ISSUE TITLE
Access to Atlassian products

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimwriterfs#101]
Atlassian -the other wiki software- might be willing to give us free access to their service : would that be enough if we were to attempt writing an Atlassian Offliner (much like Mediawiki)?

**Comment by kelson42** [comment]
@Popolechien You mean to scrape confluence, their wiki engine?

**Comment by Popolechien** [comment]
yes.

**Comment by kelson42** [comment]
no clue how confluence works in detail.

**Comment by Popolechien** [comment]
Well that was kind of my point and answers the question. Thanks.
