### ISSUE TITLE
Invalid redirection -/favicon redirecting to (missing)

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimwriterfs#119]
When specifying a favicon on the `HTML_DIRECTORY` like `--favicon=favicon.png`, a warning is displayed and the favicon is not set properly:

```
Invalid redirection -/favicon redirecting to (missing) f/vicon.png
```

Looking at the source, it seems that the user input of the `--favicon` option is used directly for two different things:
* Path existence check within the `HTML_DIRECTORY`
* favicon URL to redirect `-/favicon` to.

A quick work-around is to duplicate the favicon file:
* `I-favicon.png` (or `A-favicon.png` is using `-u`) for the file-existence to work.
* `favicon.png` which will be actually used to set the favicon (zimwriterfs will threat the previous one as a URL and replace 2nd char with a `/`).
* Use it with `--favicon=I-favicon.png`

**Comment by kelson42** [comment]
@mgautierfr @rgaudin I think the problem here is that the redirection might be created before the target file itself. Just moving the piece of code afterward could fixed the problem probably.
