### ISSUE TITLE
What is the purpose of zimwriterfs-macOS script

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#129]
This script is available in the `docker` directory but is not documented and I have no clue which problem it tries to solve.

**Comment by rgaudin** [comment]
It's a script that's meant to be placed in `~/bin` or so in order to have a `zimwriterfs` binary in your path that behaves like the real one but using the docker image.

I think it was done for use with scrapers that launch zimwriterfs.

I don't think it needs to be in the repository though.

**Comment by kelson42** [comment]
@rgaudin Is that macOS specific? What about moving it to `contrib/zimwriter-in-docker` (you have maybe a better name)? 

We should also write a small doc (a few sentences might be enough).

**Comment by rgaudin** [comment]
no it's not macOS specific. we can move it and I'll add some details and check that it still works as expected. It's 2y+ old and I haven't use it since then (forgot it exists).

**Comment by kelson42** [comment]
@rgaudin Will tag this ticket has "enhancement"
