### ISSUE TITLE
Add an `index-exclude` option

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimwriterfs#133]
Currently, zimwriterfs indexes all article which Mime-Type contains `text/html` (`Article::shouldIndex()`).

Several scrapers now integrates a sort of browsing component to access the content. Such browsing usually means pagination as well.
Because HTML content is always indexed, it is always implemented in javascript with the side effects of usability issue and dependency to javascript.

I believe it would be a nice addition to be able to exclude some articles from:

* the index (not being shown in full-text index results)
* the jump-to-article feature of the search bar
* the random article feature.

It could be an `--index-exclude` option accepting a file path containing a list of the articles to exclude.

**Comment by kelson42** [comment]
@rgaudin I don't fully understand the problem... as there is no concrete example. But this seems to be part of the solution https://github.com/openzim/libzim/blob/master/src/xapian/htmlparse.cc#L260

**Comment by rgaudin** [comment]
OK, imagine the following use-case for youtube (not perfect example as youtube needs JS support anyway)

* we have pagination done completely in JS
* we could generate homepage and all pagination pages in HTML
* it would be simpler and lighter for browsers
* it would not require JS for *browsing*
* it would have very limited size impact (small page, compression-friendly)

We're not doing it because all those *non-content/navigation pages* would show up in a search, in the auto-complete search box and in Random feature.

I think it would be relatively easy to implement:

* Add exclusion information
* change `Article::shouldIndex()` to only respond based on this list
* change random feature to look-for this information
* change auto-suggest feature to look-for this information

**Comment by kelson42** [comment]
To me, using JS with JSON data file for this kind of thing is the proper way and AFAIK user don't really complain that we are using it.
