### ISSUE TITLE
Incorrect mimetype for links containing sharp

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimwriterfs#140]
When a link contains a `#` character, zimwriterfs correctly considers it as being the _hash_ separator of the URL, thus guesses the destination mime type from the left part of the `#`.

Incorrectly though, it applies the same logic to `%23` which represents a `#` but is not (that's why it's urlencoded to `%23`.

This results in all links containing `%23` to be considered binary and thus assigned the `/I` namespace. If the link is to `c%23.html` for instance, the rewritten link will be `/I/c%23.html` instead of `/A/c%23.html`.

**reproduce**

```
mkdir -p build
wget -O build/favicon.png http://download.kiwix.org/other/youscribe/favicon.png
printf '<html><h1>hello from c#.html</h1></html>' > build/c#.html
printf '<html><a href="c%23.html">go to c#.html</a></html>' > build/home.html
zimwriterfs -w home.html -f favicon.png -l eng -t test -d test -c kiwix -p kiwix build/ link-err.zim
```

Originally reported in openzim/sotoki/issues/86

**Comment by kelson42** [comment]
@rgaudin Looks like a but in zimwriterfs indeed.
