### ISSUE TITLE
Zim-ing Hugo output

### ISSUE THREAD

**Issue by teran-mckinney** [openzim/zimwriterfs#143]
Hi,

I'm having some issues making a Zim from my blog which is made with Hugo, a Golang static site generator.

The index works, random pages work (but don't load CSS properly), any direct links don't work.

It sounds like this is expecting relative links? Is there an option to rewrite them? Having absolute links seems pretty common to me.

Here's the input: https://github.com/teran-mckinney/teran-mckinney.github.io

Thanks,

Teran

PS: I am using version 1.2 on Debian 10. Not sure if that's significantly out of date or not.

**Comment by teran-mckinney** [comment]
Same issue with 1.3.8.

**Comment by teran-mckinney** [comment]
Switched to relative URLs and still having issues. At least on random pages the CSS is loaded correctly.

Relative URLs in Hugo are prefixed with ./ -- maybe that's why? I am not familiar with the /I/ /A/ link conventions in the Zim.

**Comment by kelson42** [comment]
It is difficult to see what goes wrong with a concreate small example I can reproduce. The stuff with relative URLS starting with "./" might be but needs to be confirmed.

**Comment by teran-mckinney** [comment]
Ok! Will come up with a test case here.

**Comment by teran-mckinney** [comment]
I made this with: `zimwriterfs --welcome=index.html --favicon=favicon-120.png --language=en --title=143-test --creator Teran --publisher=Teran --description 143 143-test 143-test.zim`

The single page link works fine, but the directory link does not.

[143-test.tar.gz](https://github.com/openzim/zimwriterfs/files/4472585/143-test.tar.gz)

**Comment by kelson42** [comment]
@teran-mckinney Directory autoindex feature is not a feature we propose in Kiwix (this has nothing to do with ZIM). If you want to have thisfeature working, create an HTML page which lists your content.

**Comment by teran-mckinney** [comment]
Alright, thank you.
