### ISSUE TITLE
Cleaning the redirects (at the end of the ZIM creation file process) takes too long

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#15]
By creating the ZIM files for StackOverflow this part of the process takes many days and seems to never end... It looks like something goes wrong here.

**Comment by mgautierfr** [comment]
This is probably related to https://github.com/openzim/libzim/issues/31

**Comment by kelson42** [comment]
See also https://github.com/openzim/zimwriterfs/issues/33

**Comment by kelson42** [comment]
We still have a map, but things have been done in a way it is a lot faster. This should be good enough as this use case (a lot of wrong redirects) should not happen in normal case.
