### ISSUE TITLE
[SUSPECT] Sporadic invalid files created by zimwriterfs

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#18]
In June, we have started to generate sporadically invalid ZIM files, without having zimwriterfs complaining about anything (looks like).

It all started with the creation of random StackExchange broken ZIM files. I thought first that this is somehow specific to the version of zimwriterfs I'm running on that system... or maybe specific to something related to SE. But in fact this also happens time to time with other kind of ZIM files.

The symptom is always the same, like here:
```
./kiwix-serve --verbose --port=8080 /var/tmp.kiwix.org/wikipedia_ru_all_novid_2017-09.zim
error 2 opening file "/var/tmp.kiwix.org/wikipedia_ru_all_novid_2017-09.zim": No such file or directory
Unable to add the ZIM file '/var/tmp.kiwix.org/wikipedia_ru_all_novid_2017-09.zim' to the internal library.
```

I suspect zimwriterfs (writer part) more than the zimlibe (reader part) because with old versions of kiwix-serve it also fails to read the file.

@mgautierfr I kind of suspect that we have built here a nasty (because sporadic) regression in the zimwriterfs. Any idea about that?

**Comment by mgautierfr** [comment]
After a first investigation with http://download.kiwix.org/zim/stack_exchange/android.stackexchange.com_en_all_2017-07.zim, it seems that libzim tries to uncompressed a zip buffer
but cannot detect the end of the compressed stream, so it ends in a infinite loop, allocated each time a bigger buffer.

However, it seems strange that it try to uncompress a zip buffer, recent zim file should use lzma compression. 

I continue the investigation.

**Comment by mgautierfr** [comment]
@kelson42, do you have any clue about the version of zimwriterfs (and libzim) used to generate those files ?
Having a version/date range for these projects (`libzim` especially) would be helpful.

**Comment by kelson42** [comment]
I have created a new file with success (with last version of sotoki/libzim/zimwriterfs) http://download.kiwix.org/zim/stack_exchange/networkengineering.stackexchange.com_en_all_2017-10.zim

**Comment by mgautierfr** [comment]
> I suspect zimwriterfs (writer part) more than the zimlibe (reader part) because with old versions of kiwix-serve it also fails to read the file.

What is old version of `kiwix-serve` ?
http://download.kiwix.org/zim/stack_exchange/networkengineering.stackexchange.com_en_all_2017-07.zim can be read with zimDump of libzim 2.0.0 but cannot with libzim 3.0.0

I continue investigation but, if it is confirmed, it seems it's a bug in libzim (at reading), not libzim/zimwriterfs.

**Comment by mgautierfr** [comment]
But zimfile generated with libzim 2.0.0 can be read both with zimdump 2.0.0 and 3.0.0
