### ISSUE TITLE
No make file exists Error

### ISSUE THREAD

**Issue by 123survesh** [openzim/zimwriterfs#20]
Hi, 
I am trying to install zimwriterfs, for openedx.
While following the instructions given in the Read.me page I got an error,
**make: *** No targets specified and no makefile found.  Stop.**

Here is the output I got while performing 

> ./autogen.sh
> ./configure CXXFLAGS=-I../zimlib/include LDFLAGS=-L../zimlib/src/.libs
> make

https://paste.ofcode.org/ZzTsbZXedYmPSarSYxAmu3

I don't know what I am doing wrong :sweat_smile:  Please help me out.

**Comment by kelson42** [comment]
@123survesh 

```
configure: error: cannot find icu-config
```
You need to install libicu.... like the log tells you
