### ISSUE TITLE
Create a Debian package of zimwriterfs

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#25]
This would make the life of so many people easier!

Moved from https://phabricator.wikimedia.org/T96235

**Comment by kelson42** [comment]
@legoktm This is IMO, after kiwix-lib/kiwix-tool, the most urgent package we should do. What do you think?

**Comment by legoktm** [comment]
Sure, I can take a look :)

**Comment by legoktm** [comment]
Is this ready for Debianization now? From my quick skim, it would be good to have a tagged release, and document what version of libzim this depends upon.

**Comment by kelson42** [comment]
@legoktm I think so (and yes we should release/tag)
@mgautierfr What is your opinion: are we ready for a deb package?

**Comment by Bam92** [comment]
Just an up on this issue.

**Comment by LAfricain** [comment]
It's not a deb but you can already find an archive on the #31 issue.

**Comment by kelson42** [comment]
@Bam92 Nobody works directly on this package currently. But this id definiltly part of our plan to go ahead on this. You can get binaries here https://download.openzim.org/

**Comment by legoktm** [comment]
This is on my list for Debianization, but I think we need to get libzim updated first (which I'm also working on).

**Comment by legoktm** [comment]
ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900744
Initial packaging work: https://salsa.debian.org/legoktm-guest/zimwriterfs

**Comment by kelson42** [comment]
@legoktm Thank you so much. Stay tune, we are going to make a new important release of the libzim and zimwriterfs within the next 14 days. Nothing which should need a change on your packaging work... but might be good to refresh the package.

**Comment by legoktm** [comment]
zimwriterfs is now waiting for review in the Debian NEW queue: https://ftp-master.debian.org/new/zimwriterfs_1.2-1.html

I have a local patch to disable #72 for now.

**Comment by legoktm** [comment]
zimwriterfs is now in Debian unstable, and should be included in the Buster release later this year \o/

https://tracker.debian.org/news/1020219/accepted-zimwriterfs-12-1-source-amd64-into-unstable-unstable/
