### ISSUE TITLE
OSX zimwriterfs compilation failing

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#30]
_From @ISNIT0 on January 14, 2017 11:28_

I've installed libmagic with homebrew:
```bash
brew install libmagic
```
![image](https://cloud.githubusercontent.com/assets/5173131/21954531/bc0e5c70-da4b-11e6-8b6a-4e18d7eca615.png)

And successfully compiled zimlib:
![image](https://cloud.githubusercontent.com/assets/5173131/21954577/0c2dae76-da4d-11e6-87cd-1b373a004543.png)

autogen seems to run fine:
![image](https://cloud.githubusercontent.com/assets/5173131/21954533/d2403a86-da4b-11e6-9140-490840a4cbe6.png)

The following:
```bash
./configure CXXFLAGS="-I../zimlib/include -I/usr/local/include" LDFLAGS=-L../zimlib/src/.libs
```
Ends with (full logs attached):
![image](https://cloud.githubusercontent.com/assets/5173131/21954528/746bef54-da4b-11e6-9f8f-17566b787d12.png)

The final make command from the readme fails
```bash
make
```
![image](https://cloud.githubusercontent.com/assets/5173131/21954572/ed0e63f0-da4c-11e6-9d09-049023cca45b.png)

[configure.log.txt](https://github.com/wikimedia/openzim/files/705892/configure.log.txt)

Let me know if you need any more info, in the mean time I can find an old statically linked version

_Copied from original issue: wikimedia/openzim#6_

**Comment by kelson42** [comment]
Have you tried to test everything like written in the README https://github.com/wikimedia/openzim/blob/master/zimwriterfs/README.md

**Comment by kelson42** [comment]
_From @ISNIT0 on January 14, 2017 12:2_

@kelson42 Sorry, should have mentioned - I was following the OSX section of the README.

**Comment by ISNIT0** [comment]
@kelson42 See the first image, it says "libmagic-5.29 already installed"

**Comment by kelson42** [comment]
@ISNIT0 Ok, but the `configure` of zimwriterfs does not find it. It seems it does not find the `magic.h`. That means that the place where `magic.h` is not installed in a `gcc/g++` standard include directory. You will have to specify this directory on the `configure` command line with the following command `$ ./configure CXXFLAGS="-I/some/dir/"`

**Comment by kelson42** [comment]
I think this problem has been fixed, and the compilation scripts of zimwriterfs have been revamped. I close the pb.
