### ISSUE TITLE
Ubuntu 16.04 compilation failing

### ISSUE THREAD

**Issue by LAfricain** [openzim/zimwriterfs#31]
I run `./autogen.sh` and `./configure CXXFLAGS="-I../zimlib/include -I/usr/local/include" LDFLAGS=-L../zimlib/src/.libs` without problem, but during the `make` I have this issue:

```
zimwriterfs.cpp: In function ‘int main(int, char**)’:
zimwriterfs.cpp:286:17: error: cannot declare variable ‘source’ to be of abstract type ‘ArticleSource’
   ArticleSource source(filenameQueue);
                 ^
In file included from zimwriterfs.cpp:36:0:
articlesource.h:41:7: note:   because the following virtual functions are pure within ‘ArticleSource’:
 class ArticleSource : public zim::writer::ArticleSource
       ^
In file included from /usr/include/zim/writer/zimcreator.h:23:0,
                 from zimwriterfs.cpp:33:
/usr/include/zim/writer/articlesource.h:66:22: note: 	virtual zim::Blob zim::writer::ArticleSource::getData(const string&)
         virtual Blob getData(const std::string& aid) = 0;
                      ^
Makefile:532 : la recette pour la cible « zimwriterfs-zimwriterfs.o » a échouée
make: *** [zimwriterfs-zimwriterfs.o] Erreur 1
```

**Comment by kelson42** [comment]
@LAfricain Which version of both `zimwriterfs` and `libzim` do yo use? I suspect an older version of the libzim. Please try with the git master HEAD https://github.com/openzim/libzim

**Comment by kelson42** [comment]
After having tested myself, I confirm that the problem is the old version of the libzim :(

**Comment by LAfricain** [comment]
I just install libzim0v5 from the official repository. Must I compile lizim from [github](https://github.com/openzim/libzim)?
I tried to install the libzim from github, but instructions seems not so clear for me. First need I to clone the [git](https://github.com/openzim/libzim)?
I follow all the instruction till the Compilation section. When need I to clone the git repo?

**Comment by LAfricain** [comment]
`sudo apt-get install liblzma-dev libmagic-dev zlib1g-dev libgumbo-dev
cd ../zimlib && ./autogen.sh && ./configure && make && cd ../zimwriterfs`

Is cd ../zimlib right? Maybe you want to write **libzim**?
Because the `make` still failed. But I did not run t

**Comment by LAfricain** [comment]
@kelson42 you closed the issue, but what need I do to have the good version of libzim? Need I open a new issue on the libzim repo?

**Comment by kelson42** [comment]
@LAfricain Yes, please open a ticket per problem and follow the instructions in the README.

**Comment by LAfricain** [comment]
Now I think the good zimlib is install, error again:
`libtool: link: g++ --std=c++0x -Wall -O3 -o zimwriterfs zimwriterfs-zimwriterfs.o zimwriterfs-tools.o zimwriterfs-article.o zimwriterfs-articlesource.o zimwriterfs-indexer.o zimwriterfs-resourceTools.o zimwriterfs-pathTools.o zimwriterfs-mimetypecounter.o zimwriterfs-xapianIndexer.o xapian/zimwriterfs-myhtmlparse.o xapian/zimwriterfs-htmlparse.o  -L/usr/lib/x86_64-linux-gnu -licui18n -licuuc -licudata /usr/lib/x86_64-linux-gnu/libxapian.so -lgumbo -lpthread -lmagic -lz -lzim -llzma
zimwriterfs-zimwriterfs.o: In function 'main':
zimwriterfs.cpp:(.text.startup+0xa90): undefined reference to 'zim::writer::ZimCreator::setMinChunkSize(int)'
zimwriterfs-zimwriterfs.o: In function '_GLOBAL__sub_I__Z8languageB5cxx11':
zimwriterfs.cpp:(.text.startup+0x1283): undefined reference to 'zim::writer::ZimCreator::~ZimCreator()'
collect2: error: ld returned 1 exit status
Makefile:485 : la recette pour la cible « zimwriterfs » a échouée
make: *** [zimwriterfs] Erreur 1`

**Comment by kelson42** [comment]
@LAfricain First of all, please check that you do not have still the system version of the libzim of the distribution, uninstall the package if you have one.

Then you need to check that you do not have an other version locally install in /usr/local/:
```
find /usr/local -name "*libzim*"
```
if yes, remove the files. 

Then compile and install the libzim on your system like explained in the libzim README.

Rerun `sudo ldconfig`

Then, rerun ./autogen.sh and ./configure and make on zimwriterfs.

If you still have a problem please share the list of libzim related files you have in /usr/local and check that they really really are the one you just have installed.

**Comment by LAfricain** [comment]
Now it's ok! 
I'll tested it soon, thank you for help.

**Comment by LAfricain** [comment]
I compiled again on an other computer libzim successfully, zimwriterfs, also well. Now the problem is zimwriterfs doesn't find the libzim library:
`zimwriterfs: error while loading shared libraries: libzim.so.3: cannot open shared object file: No such file or directory`
Maybe I need to do some symbolic links?

**Comment by kelson42** [comment]
@LAfricain You are impacted by a bug we are working on.

Move your *.so files from /usr/local/lib/x86_64-linux-gnu/libzim.so.3.1.0 to /usr/local/lib/.

Then call "sudo ldconfig" then retry the ./configure

**Comment by LAfricain** [comment]
> Move your *.so files from /usr/local/lib/x86_64-linux-gnu/libzim.so.3.1.0 to /usr/local/lib/.

OK, after moving and ldconfig, zimwriterfs -h give me the good answer :)

**Comment by kelson42** [comment]
@LAfricain We have started to publish statically compiled versions of zimwriterfs for Linux64. For example here http://download.kiwix.org/nightly/2017-11-30/zimwriterfs_linux64_2017-11-30.tar.gz... So you could use them directly... maybe easier in the future.
