### ISSUE TITLE
Compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by moshez18** [openzim/zimwriterfs#34]
Trying to compile under Ubuntu 16.04 results in the following error:

~/Downloads/zimwriterfs-master$ make
g++ -DPACKAGE_NAME=\"zimwriterfs\" -DPACKAGE_TARNAME=\"zimwriterfs\" -DPACKAGE_VERSION=\"1.1\" -DPACKAGE_STRING=\"zimwriterfs\ 1.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"zimwriterfs\" -DVERSION=\"1.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBLZMA=1 -DHAVE_LIBZIM=1 -DHAVE_LIBZ=1 -DHAVE_LIBMAGIC=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBGUMBO=1 -DHAVE_STAT64=1 -DCLUSTER_CACHE_SIZE=16 -DDIRENT_CACHE_SIZE=512 -DLZMA_MEMORY_SIZE=128 -DENABLE_LZMA=1 -DHAVE_XAPIAN=1 -I.    --std=c++0x   -Wall   -O3 -MT zimwriterfs-zimwriterfs.o -MD -MP -MF .deps/zimwriterfs-zimwriterfs.Tpo -c -o zimwriterfs-zimwriterfs.o `test -f 'zimwriterfs.cpp' || echo './'`zimwriterfs.cpp
zimwriterfs.cpp: In function ‘int main(int, char**)’:
zimwriterfs.cpp:286:17: error: cannot declare variable ‘source’ to be of abstract type ‘ArticleSource’
   ArticleSource source(filenameQueue);
                 ^
In file included from zimwriterfs.cpp:36:0:
articlesource.h:41:7: note:   because the following virtual functions are pure within ‘ArticleSource’:
 class ArticleSource : public zim::writer::ArticleSource
       ^
In file included from /usr/include/zim/writer/zimcreator.h:23:0,
                 from zimwriterfs.cpp:33:
/usr/include/zim/writer/articlesource.h:66:22: note: 	virtual zim::Blob zim::writer::ArticleSource::getData(const string&)
         virtual Blob getData(const std::string& aid) = 0;
                      ^
Makefile:532: recipe for target 'zimwriterfs-zimwriterfs.o' failed
make: *** [zimwriterfs-zimwriterfs.o] Error 1

**Comment by kelson42** [comment]
@moshez18 Sorry for the late answer.Which version of the source code and of the libzim do you use? If you do not use the git master HEAD versions in both case, then maybe try that way.

Remark: if you just need a functional zimwriterfs, you can try with our nightly builds https://download.kiwix.org/nightly/

**Comment by kelson42** [comment]
No feedback. I close the ticket, please re-open if you have a feedback.
