### ISSUE TITLE
Fulltext index url has a surnumerous "/" and wrong namespace

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#35]
```
$ zimdump -n Z -f /fulltextIndex/xapian -i wikipedia_fr_test_2017-11.zim 
url: /fulltextIndex/xapian
	title:           Xapian Fulltext Index
	idx:             313
	namespace:       Z
	type:            article
	mime-type:       application/octet-stream+xapian
	article size:    57344

```

The `url` part should be `fulltextIndex/xapian`... Maybe we should wait to work on namespace suppression to work on that bug?

**Comment by kelson42** [comment]
@mgautierfr I also just ask me why the namespace is 'Z' and not 'X' like documented http://www.openzim.org/wiki/ZIM_file_format#Namespaces

**Comment by kelson42** [comment]
so 'X' as namespace and 'xapian' as url seems a better alternative.

**Comment by mgautierfr** [comment]
Because 'X' was for the previous full text index, embedded in the zimlib.
We never used it, but the code was here and we decided to use the `Z` namespace to not complict with articles in `X` namespace.
