### ISSUE TITLE
wikipedia_en_medicine_novid_2018-05.zim appears to break search in Kiwix JS (Windows)

### ISSUE THREAD

**Issue by kelson42** [openzim/zimwriterfs#48]
_From @Jaifroid on May 22, 2018 10:13_

@kelson42 , @mossroy , I have been preparing the WikiMed UWP app for release with wikipedia_en_medicine_novid_2018-05 which has just been released, when I notice that searching the ~~index~~ directory entries (basic search) appears to be broken. I reproduce this not only on Kiwix JS Windows, but also on Kiwix JS reference app. Entering terms in the search box produces no results even for known articles. This does not occur in either app when picking wikipedia_en_medicine_novid_2018-03. Therefore the problem would seem to be with the latest ZIM.

Has something in the ~~indexing~~ ZIM format changed? Or is it a bad encode of the file?

EDIT: I also reproduce this issue with wikivoyage_en_all_novid_2018-05.zim . I should perhaps specify that I am not referring to indexed ZIM files, I am referring to basic search (without a compiled index) of directory entries. It is still possible to jump to different articles with hyperlinks or with the random button, but no dirEntry search on these ZIMs.

_Copied from original issue: openzim/mwoffliner#332_

**Comment by kelson42** [comment]
_From @Jaifroid on May 22, 2018 10:43_

@kelson42 , search also fails on these ZIMs in the standard x86 app. I think this confirms that the issue is with the ZIMs rather than with Kiwix JS (Windows).

**Comment by kelson42** [comment]
I confirm the problem, probably a problem with zimwriterfs. Here is the file:
https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_novid_2018-05.zim

An other corrupted file https://download.kiwix.org/zim/wikipedia/wikipedia_en_wikipedia_en_computer_novid_2018-05.zim

@mgautierfr Do you know what is going on, this ZIM file has been created with the last version of zimwriterfs. Might that be that now zimwriterfs writes a *.zim file before the whole creation process is over?

**Comment by Jaifroid** [comment]
Thanks for the confirmation @mgautierfr. It also affects the x86 .exe version of Kiwix, so I think it's probably failing at a low level. We don't actually use libzim, but an xz decoder that is easier to encapsulate in JavaScript with Emscripten. The latest Wikivoyage ZIM file also fails, so I'm guessing it's a recent generalized problem.

**Comment by mgautierfr** [comment]
From what I see (and I may be wrong), recent changes in `libzim`/`zimwriterfs` should not create empty mimetype (at least, not more that before, and it was possible).

@kelson42 Is it possible that recent changes in mwoffliner create new file that libmagic cannot handle somehow ?

**Comment by kelson42** [comment]
@mgautierfr maybe, but should not be the case.

**Comment by kelson42** [comment]
Files have been removed and zimwriterfs fixed

**Comment by Jaifroid** [comment]
@kelson42 Just to add, and this may be the same issue, that the files currently on the server for Spanish WikiMed of May and March, `wikipedia_es_medicine_novid_2018-05.zim` and `wikipedia_es_medicine_novid_2018-03.zim`, are incorrectly coded, and have only three pages as far as I can tell. They should be hundreds of Mb, but are just 584K. There are currently no good Spanish WikiMed archives being served -- `wikipedia_es_medicine_2018-0?.zim` and `wikipedia_es_medicine_2018-0?.zim` seem to be affected as well. I have an old one from August last year that is 276Mb.

**Comment by Jaifroid** [comment]
@kelson42 , @mgautierfr  I'm afraid this issue isn't fixed in at least one of the latest English WikiMed. The archive `wikipedia_en_medicine_novid_2018-06.zim` has only a handful of entries in the ZIM's searchable directory. Most articles cannot be found. For example, Leukemia, Cancer, I've tested in both Kiwix JS and kiwix.exe. Should I open a new issue given the title of this one is specific to the previous ZIM? Or can one of you re-open this issue and generalize the title? (I don't have the option to re-open it.) There is a different, maybe related, issue with all the Spanish WikiMed ZIMs having almost no content (see my previous comment immediately above this one).

**Comment by mgautierfr** [comment]
This is probably the issue #55 .

**Comment by kelson42** [comment]
@mgautierfr This is IMO an other problem, the ZIM file is almost empty
@Jaifroid Thx you for the report, I have deleted these files too and open a dedicated ticket https://github.com/openzim/mwoffliner/issues/339. A new Wikimed ES ZIM file should be generated in the next days. I hope they will be OK.

**Comment by kelson42** [comment]
@Jaifroid Tested with both (extension and kiwix.exe) and I can read article. I suspect you still download an old version through a mirror. Download directly http://mirror.download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_novid_2018-06.zim

**Comment by Jaifroid** [comment]
@kelson42 Ah yes, I did download from a mirror link. Sorry, jumped the gun!

**Comment by Jaifroid** [comment]
Confirmed that search is now working with the directly downloaded ZIM. Thank you very much!
