### ISSUE TITLE
ninja install failed

### ISSUE THREAD

**Issue by dueni0** [openzim/zimwriterfs#50]
[1/7] Compiling C++ object 'src/src@@zimwriterfs@exe/zimwriterfs.cpp.o'.
FAILED: src/src@@zimwriterfs@exe/zimwriterfs.cpp.o
c++ -Isrc/src@@zimwriterfs@exe -Isrc -I../src -I/usr/local/include -I/usr/include/x86_64-linux-gnu -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Werror -std=c++11 -O0 -g -pthread  -MD -MQ 'src/src@@zimwriterfs@exe/zimwriterfs.cpp.o' -MF 'src/src@@zimwriterfs@exe/zimwriterfs.cpp.o.d' -o 'src/src@@zimwriterfs@exe/zimwriterfs.cpp.o' -c ../src/zimwriterfs.cpp
In file included from ../src/zimwriterfs.cpp:32:0:
../src/zimcreatorfs.h: In constructor ‘ZimCreatorFS::ZimCreatorFS(std::__cxx11::string)’:
../src/zimcreatorfs.h:43:24: error: no matching function for call to ‘zim::writer::ZimCreator::ZimCreator(bool)’
       mainPage(mainPage) {}
                        ^
In file included from ../src/article.h:25:0,
                 from ../src/zimwriterfs.cpp:31:
/usr/local/include/zim/writer/zimcreator.h:39:9: note: candidate: zim::writer::ZimCreator::ZimCreator(int&, char**)
         ZimCreator(int& argc, char* argv[]);
         ^
/usr/local/include/zim/writer/zimcreator.h:39:9: note:   candidate expects 2 arguments, 1 provided
/usr/local/include/zim/writer/zimcreator.h:38:9: note: candidate: zim::writer::ZimCreator::ZimCreator()
         ZimCreator();
         ^
/usr/local/include/zim/writer/zimcreator.h:38:9: note:   candidate expects 0 arguments, 1 provided
../src/zimwriterfs.cpp: In function ‘int main(int, char**)’:
../src/zimwriterfs.cpp:285:14: error: ‘class ZimCreatorFS’ has no member named ‘setIndexing’
   zimCreator.setIndexing(withFullTextIndex, language);
              ^
../src/zimwriterfs.cpp:286:14: error: ‘class ZimCreatorFS’ has no member named ‘startZimCreation’
   zimCreator.startZimCreation(zimPath);
              ^
[3/7] Compiling C++ object 'src/src@@zimwriterfs@exe/tools.cpp.o'.
ninja: build stopped: subcommand failed.

**Comment by dueni0** [comment]
ok now, newer libzim is required. Installing with docker instructions, I changed the line 45 from _cd libzim && git checkout 3.0.0_ to _cd libzim && git checkout_

**Comment by kelson42** [comment]
@dueni0 What is the version of the software? How have you installed ninja? Which command(s) do you run exactly? Without more details about what you are doing, it will be difficult to help you.

**Comment by dueni0** [comment]
I used the git checkout 3.0.0 command, but without version number it uses the latest 3.3.0 and then it works.
