### ISSUE TITLE
docker container does not build

### ISSUE THREAD

**Issue by tim-moody** [openzim/zimwriterfs#6]
in zimwriterfs/docker
docker build -t zimwriterfs .

Step 3/40 : RUN locale-gen "en_US.UTF-8"
 ---> Running in 7864982cc719
/bin/sh: 1: locale-gen: not found

**Comment by kelson42** [comment]
@tim-moody  Will have a look, better use directly the image https://hub.docker.com/r/openzim/zimwriterfs/

**Comment by kelson42** [comment]
Fixed
