### ISSUE TITLE
meson doesn't enforce useful permissions on libzim.pc

### ISSUE THREAD

**Issue by AVGP** [openzim/zimwriterfs#66]
I have been following the README instructions both here and in libzim but can't get it to build on Ubuntu.

I installed libzim like this:
```
$ git clone ...
$ git checkout 4.0.0
$ meson . build
$ ninja -C build
$ sudo ninja -C install
$ sudo ldconfig
```

This produces the files you'd expect:

```
ls /usr/local/lib | grep zim
libzim.so
libzim.so.4
libzim.so.4.0.0
```
as well as the "zim" directory and header files in `/usr/local/include`. ldconfig also shows me libzim when printing its cache.

However, running `meson . build` in my local copy of the `master` from zimwriterfs gives me:

```
$ meson . build
The Meson build system
Version: 0.42.1
Source dir: /home/avgp/code/zimwriterfs
Build dir: /home/avgp/code/zimwriterfs/build
Build type: native build
Project name: zimwriterfs
Native C compiler: cc (gcc 7.3.0)
Native C++ compiler: c++ (gcc 7.3.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES

Meson encountered an error in file meson.build, line 17, column 0:
C++ library 'zim' not found
```

As it turns out, pkg-config doesn't know about the library either:

```
$ pkg-config --list-all | grep zim
$
```

I've seen someone else run into the same problem here and Emmanuel can vouch for this to be an issue, too.

Now, here's a pretty manual workaround that got me a working version of zimwriterfs anyway:

1. overwrite line 17 of the meson.build file with `libzim_dep = compiler.find_library('zim', dirs: ['/usr/local/lib'])`
2. run `meson . build` which should now succeed
3. run `ninja -C build` which will compile but fail during linking
4. copy the command line (starts with `c++` and ends with `-rpath-link`
5. change into the `build folder`
6. change the command and add the following **directly following -lmagic** (or anywhere between the group start and end): `-licui18n -lstdc++ -licuuc`
7. the binary is in build/src/zimwriterfs

**Comment by AVGP** [comment]
I have an update to this: It turns out that it's a permission issue on this linux machine.

```
$ pkg-config --list-all | grep zim
$ sudo pkg-config --list-all | grep zim
libzim                         libzim - A Library to zim.
```

The problem seems to be that while other pc files have permissions set to 644, the files created by meson get the default mask of 600. Maybe meson should make sure to have 644 as permissions enforced on the file it creates?

**Comment by kelson42** [comment]
@AVGP uses a "custom" Debian based OS, I strongly suspect a wrong root user mask (or similar). @mgautierfr Maybe meson should secure that the permissions of the *.pc file are OK?

**Comment by kelson42** [comment]
We won't do anything here. Nobody else has complained and we should not make the compilation solution more complex for "nothing".
