### ISSUE TITLE
Issue while creating Zim file

### ISSUE THREAD

**Issue by sushmitapundir** [openzim/zimwriterfs#68]
Hi kelson,

I need your help to create a zim file for kiwix-server. 
I did same instruction as given in your wikipedia link -http://www.openzim.org/wiki/Zimwriterfs_instructions
But I got an error message always after runs this command - "zimwriterfs --uniqueNamespace -w apps/home.html -f icon.png -l EN -t "Testing Zim file" -d "Syntrosys content zim file" -c "Syntrosys developer" -p "Syntrosys" /vagrant/demo-syntro-content /vagrant/demo-syntro-content/result.zim".
My website is under the VM /vagrant. 

Please help me out. 
Thanks in advance.

Sushmita

**Comment by kelson42** [comment]
@sushmitapundir No feedback, I'll have to close that issue, please reopen it if necesary.
