### ISSUE TITLE
binary uses rpath, which Debian doesn't want

### ISSUE THREAD

**Issue by legoktm** [openzim/zimwriterfs#72]
(sorry, accidentally hit enter too fast)

Ever since switching to meson, the binary has rpath set, which Debian's lintian raises as an error. See
* https://lintian.debian.org/tags/binary-or-shlib-defines-rpath.html
* https://wiki.debian.org/RpathIssue

Is it necessary to set an RPATH?

**Comment by kelson42** [comment]
@mgautierfr Could you please give a feedback to @legoktm, his work on Debian packaging of zimwriterfs goes ahead quickly and an answer to that question would help him.

**Comment by kelson42** [comment]
@legoktm let us know if you have other blockers for the Debian packaging please.
