### ISSUE TITLE
Where are the titles of the html files defined?

### ISSUE THREAD

**Issue by tim-st** [openzim/zimwriterfs#73]
When I use Kiwix I can search for words and get a list of article names.
I want to know, where I can define an article name for a html file (like below where I can do it for redirects in a tsv file). Or are these parsed from a html document? If so, what happens if my html file doesn't has a title?

Also I read that I can pass a list of redirect information like
`list.tsv`
```
NAMESPACE	URL	TITLE	TARGET_URL  
```
I assume
* `URL` doesn't need to exist as a file
* `TITLE` is searchable too when using Kiwix

is it correct?

When I want to put all files (html files and images) in the same directory and make sure that it is usable in a browser, is it necessary to define a namespace?

**Comment by kelson42** [comment]
The article name comes from the HTML title and from the filename otherwise. Your assumption for the TSV are correct. Namespace are sofar mandatory yes, and are not related to the files on the fs. http://www.openzim.org/wiki/ZIM_file_format#Namespaces

**Comment by tim-st** [comment]
Thanks for the quick response. Then I will add each file a html title, so I can use short filenames.
