### ISSUE TITLE
Support woff2 font

### ISSUE THREAD

**Issue by dattaz** [openzim/zimwriterfs#74]
We currently support woff font but not woff2 font.
Apparently we should inline them (https://github.com/openzim/zimwriterfs/blob/f58bf4b874f88a5afadb3818c28b14a99f5735cf/src/article.cpp#L240:L250)

And it's seems they are not in the good namespace (I/ instead of -/)

**Comment by kelson42** [comment]
What is the mime-type? file extension?

**Comment by dattaz** [comment]
File extension : .woff2
mime-type : application/font-woff2
