### ISSUE TITLE
Process to fix content in old zims

### ISSUE THREAD

**Issue by sharun-s** [openzim/zimwriterfs#80]
I am trying to fix some issues in the content of the sample zim provided with kiwix-js https://github.com/kiwix/kiwix-js/issues/409

I was trying to use zimdump and zimwriterfs to regenerate the zim but am running into two issues.
1. It took a while to figure out zimdump generates a bunch of empty files which correspond to the redirects. What do I do with these empty redirects files?
2. During the zimwriterfs process, the links within the articles get changed to include namespace based on mimetype. So src='../-/s/style.css' turns into ../../-/-/s/style.css. Issue I guess is the links of the orignal zim's content already has namespace. 

Whats the recommended process for this kind of issue namely fixing an older zim? Do I have to dump, then run some code to clean up all the links with namespace present and then run zimwriterfs? Or is there someother way?

**Comment by kelson42** [comment]
@sharun-s Please split your ticket, any problem with `zimdump` (please give the exact command you are running and the list of empty files) should be reported in the "zim-tools" repository.

**Comment by kelson42** [comment]
@sharun-s It is so far "impossible" to fix an old ZIM file. If you have a problem with the ZIM file about Ray Charles. Please open one ticket per problem in the repo `mwoffliner`

**Comment by sharun-s** [comment]
Ah I was beginning to sense the "impossibility" :)

Commands used -
Was run in the kiwix-js/www dir
`zimdump -v -D ray wikipedia_en_ray_charles_2015-06.zim`

In the ray directory, to see the list of empty files generated (which correspond to all the redirect titles in the zim)
`find . -size 0c` 

After fixing content regenerate zim with -
`zimwriterfs -v -w A/Summary -f I/favicon.png -l EN -t "Ray Charles" -d"Sample ZIM file for testing" -c "kiwix" -p "kiwix" ray/ Ray_Charles.zim`

Will add issues to zim-tools and mwoffliner

**Comment by kelson42** [comment]
@sharun-s As you have open dedicated issue in the right repo, thx for them, I will close that ticket.

**Comment by sharun-s** [comment]
Since I am quite sure I will forget the process by next week I wrote down the steps I used to modify the zim here /sharun-s/kiwix-html5/issues/5 Maybe of use to others...
