### ISSUE TITLE
zimwriterfs as a web service?

### ISSUE THREAD

**Issue by samuk** [openzim/zimwriterfs#87]
Have you considered making zimwriterfs a web service?

I'm imagining a tool similar to https://www.online-convert.com/ where you upload a folder of contents, press 'convert' and it spits out a .zim file?

I realise it might not be entirely straightforward, but would make zim creation much more accessible IMHO

**Comment by kelson42** [comment]
@samuk Have a look to https://zip2zim.openzim.org/

**Comment by samuk** [comment]
Nice :)
