### ISSUE TITLE
question: Very small zim created.

### ISSUE THREAD

**Issue by nobicycle** [openzim/zimwriterfs#90]
Hi,

I tested zimwritefs but without success. 

I extracted  a zim as follows

> $ zimdump -D fred ./teded_en_all_2017-10.zim

Then I tried to create a zim from the extract as follows:

> $ zimwriterfs -v -i -w "3 things I learned while my plane crashed - Ric Elias" -f ../I/favicon.png -l en -t 'djdj' -d 'djd kdkk' -c 'djdj' -p 'dkdk' ./fred/A fred.zim
> Visiting directory ./fred/A
> A:1000; CA:999; UA:1; FA:0; IA:991; C:2; CC:2; UC:0
> Reading redirects TSV file ...
> A:1419; CA:1418; UA:1; FA:0; IA:1409; C:2; CC:2; UC:0
> sort 1420 directory entries (aid)
> remove invalid redirects from 1420 directory entries
> 0/1420 directory entries checked for invalid redirects
> remove invalid redirection favicon redirecting to (missing) ../I/favicon.png
> 0/1419 directory entries checked for invalid redirects
> sort 1419 directory entries (url)
> set index
> translate redirect aid to index
> create title index
> 1419 title index created
> 4 clusters created
> fill header
> write zimfile
> ready

> 
A  small zim of 1.5 MB is created, in comparison to the original 20GB

> $ ls fred.zim -lh
> -rw-r--r-- 1 me me 1.5M Dec 24 19:13 fred.zim
> 

For the -w option I just chose a random html file, but perhaps zimewritefs uses it to parse the content, which would explain the small file? If that is true I'll need to create a proper index html page.

**Comment by nobicycle** [comment]
Hello kelson42
As mentioned, I was I testing zimwritefs using an already existing zim. 
Understood about the dump.

What should be the content of the file corresponding with the -W option. The top level index.html of an html tree which is parsed by zimwritefs?

**Comment by kelson42** [comment]
@nobicycle Welcome page is an HTML page, it is the "default" page displayed. You put whatever you want in it.
