### ISSUE TITLE
Wikipedia (DE) Zim file with images has problems

### ISSUE THREAD

**Issue by tim-st** [openzim/zimwriterfs#91]
I think the kiwix files (here: `wikipedia_de_all_novid_2018-11.zim` ) are built with `zimwriterfs` so I post it here:
When I load the file with kiwix (and also with my implementation `nim-zim`) some images can't load.
An example is the wikipedia article "Sand" or also "Taubenschwänzchen" that can't display the images.
Most images in most articles work good though.
I'm not sure if the image files are actually included in the Zim files and it's just a linking error or if they got lost.

**Comment by tim-st** [comment]
Here is how it looks in Kiwix and my implementation:
[Taubenschwänzchen.pdf](https://github.com/openzim/zimwriterfs/files/2817619/Taubenschwanzchen.pdf)

**Comment by kelson42** [comment]
@tim-st have you check with kiwix-serve (part of the kiwix-tools)? You can also inspect the content with zimdump (part of zim-tools).

**Comment by tim-st** [comment]
For me the kiwix-tools crash directly when I try to use them (Windows 7 x64).
When I load the article `Taubenschwänzchen` using `kiwix-desktop_windows_x64_2.0-beta2` there are no images. And I see the exact same behaviour using my implementation. I assume a bug in the created file.
My Zim file `wikipedia_de_all_novid_2018-11.zim` is correct:
```
Calculating MD5 checksum for ZIM file with name: kiwix.wikipedia_de_all.
Please wait...
Internal checksum was:   45619e5ace8ada7ba501c58d2777f19b
Calculated checksum was: 45619e5ace8ada7ba501c58d2777f19b
```

**Comment by kelson42** [comment]
@tim-st Please virify the checksum of the file against https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_novid_2018-11.zim.mirrorlist

**Comment by tim-st** [comment]
@kelson42 Thanks, the md5 sum I posted differs from the one linked above because I meant the internal md5 sum described in the spec while the page linked has ckecksums for the whole file. I now created a SHA1 check for the whole file and it's the same as on the page.

**Comment by tim-st** [comment]
Well... Obviously it's the same issue as [here](https://github.com/openzim/mwoffliner/issues/462).

**Comment by kelson42** [comment]
@tim-st Have you moved/deleted your ZIM reader in Nim? I can not find it anymore on Github.

**Comment by tim-st** [comment]
I made it private when I finished an alternative implementation in Go that works the same and has less dependencies (is easier to build).

**Comment by kelson42** [comment]
@tim-st OK, this is a bit sad.

**Comment by tim-st** [comment]
[Here](https://github.com/openzim/zimwriterfs/files/3385446/nim-zim-master.zip)  is an archived version from last master.

**Comment by kelson42** [comment]
@tim-st Thank you, I have updated https://wiki.openzim.org/wiki/Readers
